import type { Prisma } from "@prisma/client";
import prisma from "./prisma";

export interface AuditLogParams {
  actorId?: string | null;
  actorEmail?: string | null;
  actorRole?: string | null;
  action: string;
  entityType?: string | null;
  entityId?: string | null;
  metadata?: Record<string, unknown> | null;
  ipAddress?: string | null;
  userAgent?: string | null;
}

export async function createAuditLog(params: AuditLogParams): Promise<void> {
  try {
    await prisma.auditLog.create({
      data: {
        actorId: params.actorId ?? null,
        actorEmail: params.actorEmail ?? null,
        actorRole: params.actorRole ?? null,
        action: params.action,
        entityType: params.entityType ?? null,
        entityId: params.entityId ?? null,
        metadata: (params.metadata ?? undefined) as Prisma.InputJsonValue | undefined,
        ipAddress: params.ipAddress ?? null,
        userAgent: params.userAgent ? params.userAgent.slice(0, 500) : null,
      },
    });
  } catch (err) {
    console.error("[audit] Failed to create audit log:", err);
  }
}

export function getRequestMeta(request: Request) {
  const forwarded = request.headers.get("x-forwarded-for");
  const ipAddress = forwarded ? forwarded.split(",")[0].trim() : "unknown";
  const userAgent = request.headers.get("user-agent") || undefined;
  return { ipAddress, userAgent };
}

export async function auditUserAction(
  request: Request,
  userId: string,
  email: string,
  action: string,
  extra?: { entityType?: string; entityId?: string; metadata?: Record<string, unknown> }
): Promise<void> {
  const { ipAddress, userAgent } = getRequestMeta(request);
  await createAuditLog({
    actorId: userId,
    actorEmail: email,
    actorRole: "user",
    action,
    entityType: extra?.entityType,
    entityId: extra?.entityId,
    metadata: extra?.metadata,
    ipAddress,
    userAgent,
  });
}

export async function auditAdminAction(
  request: Request,
  adminId: string,
  email: string,
  action: string,
  extra?: { entityType?: string; entityId?: string; metadata?: Record<string, unknown> }
): Promise<void> {
  const { ipAddress, userAgent } = getRequestMeta(request);
  await createAuditLog({
    actorId: adminId,
    actorEmail: email,
    actorRole: "admin",
    action,
    entityType: extra?.entityType,
    entityId: extra?.entityId,
    metadata: extra?.metadata,
    ipAddress,
    userAgent,
  });
}

export const AUDIT_ACTIONS = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_EXTRACTION_STARTED: "DOCUMENT_EXTRACTION_STARTED",
  DOCUMENT_EXTRACTION_FAILED: "DOCUMENT_EXTRACTION_FAILED",
  DOCUMENT_EXTRACTION_COMPLETED: "DOCUMENT_EXTRACTION_COMPLETED",
  AI_SUMMARY_STARTED: "AI_SUMMARY_STARTED",
  AI_SUMMARY_COMPLETED: "AI_SUMMARY_COMPLETED",
  AI_SUMMARY_FAILED: "AI_SUMMARY_FAILED",
  AI_SUMMARY_REGENERATED: "AI_SUMMARY_REGENERATED",
  REPORT_CONTEXT_SAVED: "REPORT_CONTEXT_SAVED",
  REPORT_CONTEXT_SKIPPED: "REPORT_CONTEXT_SKIPPED",
  AI_SUMMARY_GENERATED_WITH_CONTEXT: "AI_SUMMARY_GENERATED_WITH_CONTEXT",
  PDF_DOWNLOADED: "PDF_DOWNLOADED",
  DOCUMENT_LINKED_TO_FAMILY_MEMBER: "DOCUMENT_LINKED_TO_FAMILY_MEMBER",

  FAMILY_MEMBER_CREATED: "FAMILY_MEMBER_CREATED",
  FAMILY_MEMBER_UPDATED: "FAMILY_MEMBER_UPDATED",
  FAMILY_MEMBER_DELETED: "FAMILY_MEMBER_DELETED",
  FAMILY_CONDITION_ADDED: "FAMILY_CONDITION_ADDED",
  FAMILY_CONDITION_UPDATED: "FAMILY_CONDITION_UPDATED",
  FAMILY_CONDITION_DELETED: "FAMILY_CONDITION_DELETED",
  FAMILY_ALLERGY_ADDED: "FAMILY_ALLERGY_ADDED",
  FAMILY_ALLERGY_UPDATED: "FAMILY_ALLERGY_UPDATED",
  FAMILY_ALLERGY_DELETED: "FAMILY_ALLERGY_DELETED",
  FAMILY_MEDICATION_ADDED: "FAMILY_MEDICATION_ADDED",
  FAMILY_MEDICATION_UPDATED: "FAMILY_MEDICATION_UPDATED",
  FAMILY_MEDICATION_DELETED: "FAMILY_MEDICATION_DELETED",
  FAMILY_VITAL_ADDED: "FAMILY_VITAL_ADDED",
  FAMILY_VITAL_UPDATED: "FAMILY_VITAL_UPDATED",
  FAMILY_VITAL_DELETED: "FAMILY_VITAL_DELETED",
  FAMILY_APPOINTMENT_ADDED: "FAMILY_APPOINTMENT_ADDED",
  FAMILY_APPOINTMENT_UPDATED: "FAMILY_APPOINTMENT_UPDATED",
  FAMILY_APPOINTMENT_DELETED: "FAMILY_APPOINTMENT_DELETED",
  FAMILY_EMERGENCY_CONTACT_ADDED: "FAMILY_EMERGENCY_CONTACT_ADDED",
  FAMILY_EMERGENCY_CONTACT_UPDATED: "FAMILY_EMERGENCY_CONTACT_UPDATED",
  FAMILY_EMERGENCY_CONTACT_DELETED: "FAMILY_EMERGENCY_CONTACT_DELETED",

  REMINDER_CREATED: "REMINDER_CREATED",
  REMINDER_UPDATED: "REMINDER_UPDATED",
  REMINDER_DELETED: "REMINDER_DELETED",
  REMINDER_MARKED_DONE: "REMINDER_MARKED_DONE",
  REMINDER_MARKED_SKIPPED: "REMINDER_MARKED_SKIPPED",
  REMINDER_CANCELLED: "REMINDER_CANCELLED",
  NOTIFICATION_PERMISSION_REQUESTED: "NOTIFICATION_PERMISSION_REQUESTED",

  SEARCH_PERFORMED: "SEARCH_PERFORMED",
  INSIGHTS_GENERATED: "INSIGHTS_GENERATED",
  INSIGHT_MARKED_READ: "INSIGHT_MARKED_READ",
  INSIGHT_DELETED: "INSIGHT_DELETED",
  REPORT_COMPARISON_VIEWED: "REPORT_COMPARISON_VIEWED",
  VITAL_TRENDS_VIEWED: "VITAL_TRENDS_VIEWED",

  DOCTOR_SHARE_LINK_CREATED: "DOCTOR_SHARE_LINK_CREATED",
  DOCTOR_SHARE_LINK_REVOKED: "DOCTOR_SHARE_LINK_REVOKED",
  DOCTOR_SHARE_LINK_ACCESSED: "DOCTOR_SHARE_LINK_ACCESSED",
  DOCTOR_QUESTIONS_GENERATED: "DOCTOR_QUESTIONS_GENERATED",
  MEDICATION_DOSE_TAKEN: "MEDICATION_DOSE_TAKEN",
  MEDICATION_DOSE_MISSED: "MEDICATION_DOSE_MISSED",
  MEDICATION_DOSE_SKIPPED: "MEDICATION_DOSE_SKIPPED",
  HEALTH_RISKS_VIEWED: "HEALTH_RISKS_VIEWED",
  HEALTH_RISKS_EXTRACTED_FROM_REPORT: "HEALTH_RISKS_EXTRACTED_FROM_REPORT",
  INSIGHTS_CREATED_FROM_REPORT: "INSIGHTS_CREATED_FROM_REPORT",
  LAB_TRENDS_EXTRACTED_FROM_REPORT: "LAB_TRENDS_EXTRACTED_FROM_REPORT",
  REMINDER_SUGGESTIONS_CREATED: "REMINDER_SUGGESTIONS_CREATED",
  NOTIFICATION_CREATED_FROM_REPORT: "NOTIFICATION_CREATED_FROM_REPORT",
  REPORT_POST_PROCESSING_COMPLETED: "REPORT_POST_PROCESSING_COMPLETED",
  HEALTH_RISK_DISMISSED: "HEALTH_RISK_DISMISSED",
  HEALTH_RISK_RESOLVED: "HEALTH_RISK_RESOLVED",
  REMINDER_SUGGESTION_ACCEPTED: "REMINDER_SUGGESTION_ACCEPTED",
  REMINDER_SUGGESTION_DISMISSED: "REMINDER_SUGGESTION_DISMISSED",
  LAB_TEST_VIEWED: "LAB_TEST_VIEWED",
  SYMPTOM_ENTRY_CREATED: "SYMPTOM_ENTRY_CREATED",
  SYMPTOM_ENTRY_UPDATED: "SYMPTOM_ENTRY_UPDATED",
  SYMPTOM_ENTRY_DELETED: "SYMPTOM_ENTRY_DELETED",
  CAREGIVER_INVITE_CREATED: "CAREGIVER_INVITE_CREATED",
  CAREGIVER_INVITE_ACCEPTED: "CAREGIVER_INVITE_ACCEPTED",
  CAREGIVER_ACCESS_REVOKED: "CAREGIVER_ACCESS_REVOKED",
  EMERGENCY_CARD_CREATED: "EMERGENCY_CARD_CREATED",
  EMERGENCY_CARD_VIEWED: "EMERGENCY_CARD_VIEWED",
  EMERGENCY_CARD_PDF_DOWNLOADED: "EMERGENCY_CARD_PDF_DOWNLOADED",
  USER_PREFERENCES_UPDATED: "USER_PREFERENCES_UPDATED",

  MOCK_PLAN_CHANGED: "MOCK_PLAN_CHANGED",
  RAZORPAY_ORDER_CREATED: "RAZORPAY_ORDER_CREATED",
  RAZORPAY_PAYMENT_VERIFIED: "RAZORPAY_PAYMENT_VERIFIED",
  USAGE_UPLOAD_INCREMENTED: "USAGE_UPLOAD_INCREMENTED",
  USAGE_AI_INCREMENTED: "USAGE_AI_INCREMENTED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  EMAIL_VERIFICATION_SENT: "EMAIL_VERIFICATION_SENT",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  ONBOARDING_SKIPPED: "ONBOARDING_SKIPPED",
  USER_LEGAL_CONSENT_ACCEPTED: "USER_LEGAL_CONSENT_ACCEPTED",
  DEMO_LOGIN: "DEMO_LOGIN",

  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_VIEWED_DASHBOARD: "ADMIN_VIEWED_DASHBOARD",
  ADMIN_VIEWED_USER: "ADMIN_VIEWED_USER",
  ADMIN_CHANGED_USER_ROLE: "ADMIN_CHANGED_USER_ROLE",
  ADMIN_UPDATED_USER_STATUS: "ADMIN_UPDATED_USER_STATUS",
  ADMIN_DELETED_DOCUMENT: "ADMIN_DELETED_DOCUMENT",
  ADMIN_DOWNLOADED_REPORT: "ADMIN_DOWNLOADED_REPORT",
  ADMIN_VIEWED_REPORT: "ADMIN_VIEWED_REPORT",
  ADMIN_CLEANUP_FILES: "ADMIN_CLEANUP_FILES",
} as const;
